### ISSUE TITLE
Rename "snakelings" everywhere to "snekilings".

### ISSUE THREAD

**Issue by THEGOLDENPRO** [THEGOLDENPRO/snakelings#8]
As the title says. There's just many places in the source code and exercises where the old "snakelings" name was used.

**Comment by Bicheka** [comment]
@THEGOLDENPRO I fixed the issue review the pull request

**Comment by THEGOLDENPRO** [comment]
Thank you, I'll have a look at the pr soon. 👍

**Comment by THEGOLDENPRO** [comment]
fixed in #9
